/**
 * Serves `dist/` and asks Chromium to print `/cv` into `dist/cv.pdf`.
 *
 * It is NO LONGER part of `pnpm run build`. The production PDF is generated by
 * `functions/cv.pdf.ts` on demand; this exists for two things: looking at the
 * PDF locally without deploying, and producing the file `pnpm run test:pdf`
 * runs against BEFORE anything is published. It is the pre-deploy gate, not the
 * generator of the deliverable.
 *
 * It is served over HTTP and not `file://` because the absolute asset paths
 * (`/_astro/...`) do not resolve from the filesystem, and the PDF would come
 * out with no fonts and no styles.
 *
 * The server is 30 lines on purpose: adding a dependency for this would be more
 * maintenance surface than the problem it solves.
 */

import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { renderPdf } from "./render-pdf";

const DIST = "dist";
const OUT = join(DIST, "cv.pdf");

const TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".txt": "text/plain; charset=utf-8",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".webp": "image/webp",
};

const server = createServer(async (req, res) => {
  // normalize() strips any `..`: the server never leaves dist/.
  const path = normalize(decodeURIComponent((req.url ?? "/").split("?")[0]));
  const candidates = [join(DIST, path), join(DIST, path, "index.html")];

  for (const file of candidates) {
    try {
      const body = await readFile(file);
      res.writeHead(200, { "content-type": TYPES[extname(file)] ?? "application/octet-stream" });
      res.end(body);
      return;
    } catch {
      // Try the next candidate.
    }
  }

  res.writeHead(404).end("not found");
});

await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
const { port } = server.address() as { port: number };

try {
  await renderPdf({ url: `http://127.0.0.1:${port}/cv`, out: OUT });
  console.log(`PDF written to ${OUT}`);
} finally {
  server.close();
}
