/**
 * Generates `public/og.jpg`: the card WhatsApp, LinkedIn, Twitter, Facebook,
 * Slack and Discord show when someone pastes the link.
 *
 * `pnpm run og:local`. It does NOT run in the build or in CI, and that is the
 * underlying decision (docs/07 §18): rasterizing needs Chromium and the
 * Cloudflare builder does not have it — the same reason the PDF left the build.
 * So the image is generated here and COMMITTED. Zero runtime cost, zero
 * dependency on the builder, and no crawler waiting for a service to print
 * something for it.
 *
 * The price of committing it is that it can go stale silently: if the name, the
 * role or the photo changes, the JPEG stays the old one. That is why, alongside
 * the JPEG, `og.lock.json` is written with the fingerprint of the inputs, and
 * `og-output.check.ts` fails in CI when one does not match the other.
 *
 * The tags pointing at this image live in `src/layouts/Base.astro`.
 */

import { readFile, writeFile } from "node:fs/promises";
import { chromium } from "playwright";

import { brandSvg } from "../src/lib/brand";
import { PHOTO, fingerprint, ICON, IMAGE, LOCK, BRAND, TEMPLATE, ogTexts } from "./og-data";
import { buildIconHtml, buildOgHtml, ICON_SIDE, OG_HEIGHT, OG_WIDTH, OG_MAX_BYTES } from "./og-template";

/**
 * JPEG quality. 84 keeps the photo clean and the file well under WhatsApp's
 * ceiling; raising it to 92 doubles the size with no visible difference.
 */
const QUALITY = 84;

/** The weights the template uses. They have to exist as files. */
const WEIGHTS = [400, 600, 800] as const;

async function fontCss(): Promise<string> {
  const faces = await Promise.all(
    WEIGHTS.map(async (weight) => {
      const bin = await readFile(`node_modules/@fontsource/manrope/files/manrope-latin-${weight}-normal.woff2`);
      // Embedded as `data:` and not via a link: the template is rendered with
      // `setContent`, with no server and no network. A `<link>` to Google Fonts
      // would make the card depend on there being internet when generating it.
      return `@font-face{font-family:"Manrope";font-style:normal;font-weight:${weight};font-display:block;src:url(data:font/woff2;base64,${bin.toString("base64")}) format("woff2")}`;
    }),
  );
  return faces.join("\n");
}

async function main(): Promise<void> {
  const [texts, photo, template, brandSource] = await Promise.all([
    ogTexts(),
    readFile(PHOTO),
    readFile(TEMPLATE),
    readFile(BRAND),
  ]);

  const html = buildOgHtml({
    ...(texts as { name: string; kicker: string; role: string }),
    photoDataUri: `data:image/jpeg;base64,${photo.toString("base64")}`,
    fontCss: await fontCss(),
    brand: brandSvg({ size: 44, accent: "#b0472a", ink: "#17181c" }),
  });

  const browser = await chromium.launch();
  let jpeg: Buffer;
  let icon: Buffer;
  try {
    // Scale 1: the viewport IS the final size, so there is no rescaling to
    // soften the edges of the text.
    const page = await browser.newPage({ viewport: { width: OG_WIDTH, height: OG_HEIGHT } });
    await page.setContent(html, { waitUntil: "load" });

    // Without this Chromium can rasterize with the fallback font, and the card
    // comes out different on every machine.
    await page.evaluate(() => document.fonts.ready);

    jpeg = await page.screenshot({ type: "jpeg", quality: QUALITY });

    // The iOS icon, in the same browser: launching Chromium twice to draw
    // 180x180 would be paying two startups for a 2 KB file.
    // PNG and not JPEG: it is four flat colors, and JPEG puts artifacts right
    // on the edge of the ring, which is all you see at that size.
    const small = await browser.newPage({ viewport: { width: ICON_SIDE, height: ICON_SIDE } });
    await small.setContent(buildIconHtml(brandSvg({ size: 116, accent: "#b0472a", ink: "#17181c" })));
    icon = await small.screenshot({ type: "png" });
  } finally {
    await browser.close();
  }

  if (jpeg.byteLength > OG_MAX_BYTES) {
    throw new Error(
      `og.jpg weighs ${(jpeg.byteLength / 1024).toFixed(0)} KB and the ceiling is ${OG_MAX_BYTES / 1024} KB.\n` +
        `WhatsApp does not show the preview when it goes over. Lower QUALITY in ${import.meta.filename ?? "scripts/build-og.ts"}.`,
    );
  }

  await writeFile(IMAGE, jpeg);
  await writeFile(ICON, icon);
  await writeFile(
    LOCK,
    JSON.stringify(
      {
        _: "Generated by `pnpm run og:local`. Do NOT edit by hand: og-output.check.ts compares it against the dataset.",
        fingerprint: fingerprint(texts, photo, template, brandSource),
        width: OG_WIDTH,
        height: OG_HEIGHT,
        texts,
      },
      null,
      2,
    ) + "\n",
  );

  console.log(
    `og.jpg — ${(jpeg.byteLength / 1024).toFixed(0)} KB of ${OG_MAX_BYTES / 1024} KB · ` +
      `apple-touch-icon.png — ${(icon.byteLength / 1024).toFixed(1)} KB`,
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
